"""Strict allowlist-based Cypher safety check for user-supplied queries.

Used at three entry points:
  - api/routes/query.py     — direct Cypher from the dashboard
  - api/routes/nl.py        — Cypher generated by the NL LLM
  - pipeline/stage5_er.py   — manifest stage5_er_rules[].cypher (uploaded YAML)
  - pipeline/stage6_validate.py — manifest stage6_checks[].cypher (uploaded YAML)

Approach: tokenise (strip comments + string literals) then enforce that no
forbidden keyword appears at a top-level token boundary. Forbidden keywords
cover writes, schema changes, catalog mutations, file/HTTP I/O via APOC, and
arbitrary procedure calls. Approach is conservative — false positives are
acceptable for a dev tool.
"""
from __future__ import annotations
import re


# Block all writes, all schema mutations, all catalog mutations, and all
# procedure calls (even read ones) — APOC has too many sharp edges to allowlist
# individually. Cypher reads stay open: MATCH, OPTIONAL MATCH, WITH, WHERE,
# RETURN, ORDER BY, LIMIT, SKIP, UNWIND, UNION, plus expression functions.
_FORBIDDEN = {
    # writes
    "CREATE", "MERGE", "DELETE", "DETACH", "SET", "REMOVE",
    # schema / catalog
    "DROP", "ALTER", "CONSTRAINT", "INDEX", "RENAME", "GRANT", "REVOKE",
    # files / data loading
    "LOAD", "FOREACH", "USING", "PERIODIC",
    # procedure execution (covers apoc, n10s, dbms.*)
    "CALL",
    # database scope
    "USE", "START", "STOP", "SHOW",
}

_COMMENT_RE = re.compile(r"//.*?$|/\*.*?\*/", re.DOTALL | re.MULTILINE)
# Match either single- or double-quoted string literals, including escapes.
_STRING_RE = re.compile(r"'(?:\\.|[^'\\])*'|\"(?:\\.|[^\"\\])*\"")
_TOKEN_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")


class UnsafeCypherError(ValueError):
    """Raised when a Cypher string contains a forbidden keyword."""


def strip_literals(cypher: str) -> str:
    """Remove comments and string literals so keyword detection sees only structural tokens."""
    no_comments = _COMMENT_RE.sub(" ", cypher)
    no_strings = _STRING_RE.sub(" ", no_comments)
    return no_strings


def find_forbidden_tokens(cypher: str) -> list[str]:
    """Return the set of forbidden uppercase tokens present in the (stripped) query.

    Tokens that immediately follow `.` are property accesses (e.g. `n.show`,
    `node.start`) and never refer to Cypher keywords — those are skipped to
    avoid false positives on legitimate read queries.
    """
    stripped = strip_literals(cypher)
    upper = stripped.upper()
    found = []
    for m in _TOKEN_RE.finditer(upper):
        tok = m.group(0)
        if tok not in _FORBIDDEN or tok in found:
            continue
        # Look one char back, skipping whitespace, for a `.` — property access.
        i = m.start() - 1
        while i >= 0 and upper[i].isspace():
            i -= 1
        if i >= 0 and upper[i] == ".":
            continue
        found.append(tok)
    return found


def assert_read_only(cypher: str, *, source: str = "query") -> None:
    """Raise UnsafeCypherError if `cypher` contains any forbidden keyword.

    `source` is included in the message to help operators trace where the
    rejected query came from (manifest, NL endpoint, raw query console).
    """
    bad = find_forbidden_tokens(cypher)
    if bad:
        raise UnsafeCypherError(
            f"{source} contains forbidden keyword(s) {bad}; only read queries are permitted."
        )
